auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            FangHow.com
url:              http://www.fanghow.com
feed:             /atom.xml
author:
    name:         FangHow
    twitter:      chinafanghao
description:      "FangHow\'s Blog"
author_info:      <a href="http://www.fanghow.com/about">FangHow</a>

copyright:
    - Design by <a href="http://www.fanghow.com/about" title="FangHow" target="_blank">FangHow</a> &copy; 2013
